apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: htpasswd
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpass-8jvqm
[mlele@mlele tmp]$ cat secret.yml 
apiVersion: v1
data:
  htpasswd: YWRtaW5pc3RyYXRvcjokMnkkMDUkdDhiNTJLaDBSd2VQNHlGcGFMQW9MLkh2d1drZUJvZWouUUZOZGdLN3NlLzVLWnVUVnFxT2EK
kind: Secret
metadata:
  creationTimestamp: null
  name: htpasswd-8jvqm
  namespace: openshift-config

